//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrzeEngine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GrzeEngine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string static2DFragmentShader {
            get {
                return ResourceManager.GetString("static2DFragmentShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 330
        ///
        ///in vec3 color;
        /// 
        ///void main(void)
        ///{
        ///  gl_FragColor = vec4(color, 1);
        ///}.
        /// </summary>
        internal static string static2DFragmentShader1 {
            get {
                return ResourceManager.GetString("static2DFragmentShader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 330
        ///
        ///uniform mat4 projection_matrix;
        ///uniform mat4 view_matrix;
        ///uniform mat4 transformation_matrix;
        /// 
        ///out vec3 color;
        /// 
        ///attribute vec2 in_position;
        /// 
        ///void main(void)
        ///{
        ///  gl_Position = projection_matrix * view_matrix * transformation_matrix * vec4(in_position, 0, 1);
        ///  color = vec3(in_position.x / 10, in_position.y / 10, 0);
        ///}.
        /// </summary>
        internal static string static2DVertexShader {
            get {
                return ResourceManager.GetString("static2DVertexShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 330
        ///
        ///in vec3 color;
        /// 
        ///void main(void)
        ///{
        ///  gl_FragColor = vec4(color, 1);
        ///}.
        /// </summary>
        internal static string staticFragmentShader {
            get {
                return ResourceManager.GetString("staticFragmentShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 330
        ///
        ///uniform mat4 projection_matrix;
        ///uniform mat4 view_matrix;
        ///uniform mat4 transformation_matrix;
        /// 
        ///out vec3 color;
        /// 
        ///attribute vec3 in_position;
        /// 
        ///void main(void)
        ///{
        ///  gl_Position = projection_matrix * view_matrix * transformation_matrix * vec4(in_position, 1);
        ///  color = vec3(in_position.x+0.5, in_position.z+0.5, in_position.y+0.5);
        ///}.
        /// </summary>
        internal static string staticVertexShader {
            get {
                return ResourceManager.GetString("staticVertexShader", resourceCulture);
            }
        }
    }
}
